### ISSUE TITLE
How am I supposed to retrieve card token?

### ISSUE THREAD

**Issue by firatakandere** [PayU/alu-client-php#16]
I follow the following example for recurring payments. It provides a function to enable generating card token but how am I supposed to get that token?

https://github.com/PayU/alu-client-php/blob/master/examples/createTokenForRecurrentPayment.php

**Comment by drealecs** [comment]
Hi @firatakandere,
I just updated the example to also point out how to read the token.
That is a call to `$response->getTokenHash()`.

Keep in mind that this is a feature that might not be available by default.
If the call to `getTokenHash()` is not returning anything, you'll have to talk with operation department to enable it.

**Comment by drealecs** [comment]
Hi @firatakandere. I would like to close this issue. Have it solved your problem?

**Comment by firatakandere** [comment]
Yes, I have just checked and I get a string with this method. Thank you very much for your help!
