### ISSUE TITLE
Payment with Token doesn't work

### ISSUE THREAD

**Issue by firatakandere** [PayU/alu-client-php#18]
Hi,

When I try this example: https://github.com/PayU/alu-client-php/blob/master/examples/tokenPayment.php

The message returns like this: `Invalid card number entered.()\nInvalid expiration date entered or the card has expired.(00-)`

Am I supposed to encode the token before using it? Because the token format I get by using this example: https://github.com/PayU/alu-client-php/blob/master/examples/createTokenForRecurrentPayment.php

is different from the format of the token used in the tokenPayment.php example.

Thanks in advance.

**Comment by drealecs** [comment]
No encoding needs to be done on the token. Usually it should be a 32 hex-digits string.

**Comment by drealecs** [comment]
I can't pinpoint the problem. There might be some operational settings to be done in order to use it.
I think it would be better to get in touch with someone from integration department and if they can't help you directly, they could open an internal issue to assist you for more technical details

**Comment by firatakandere** [comment]
I've just contacted them and they told me it's because CC_ parameters are sent as NULL but expected is empty string. So they should be like this:

`"CC_NUMBER" => "",
"EXP_MONTH" => "",
"EXP_YEAR" => "",
"CC_CVV" => "",
"CC_OWNER" => "",`

**Comment by firatakandere** [comment]
and yeah it works in that way.

**Comment by drealecs** [comment]
Sounds familiar.
If you can help to pinpoint the problem further:
Can you try to send empty only the `CC_CVV` only to check if it works?

**Comment by firatakandere** [comment]
Yep it works when I send only CC_CVV as an empty string.

**Comment by drealecs** [comment]
Thank you very much. I'll take care of the fix further.

**Comment by drealecs** [comment]
fixed
