### ISSUE TITLE
Response HASH mismatch

### ISSUE THREAD

**Issue by makbulut** [PayU/alu-client-php#9]
validateResponseHash function returns "Response HASH mismatch" exception.

**Comment by drealecs** [comment]
Hi @makbulut,
I'm not sure I can easily find exactly where the problem is.
Can you let me know how you are trying to use the client and against what instance?

Maybe you can paste an example how you are trying to used it, of course without the line with
```
new MerchantConfig('MERCHANT_CODE', 'SECRET_KEY', 'TR');
```

Thank you,
Alex

**Comment by muratunal** [comment]
I am rarely getting the same exception within the correct parameters. This is too odd that it works sometimes and not. Even it changes depending on the enviorement(local env vs production env)

I have just got into the documentation given from the Turkish PayU customer service. They state that,  the ORDER_REF, RESPONSE_CODE, RESPONSE_MESSAGE, DATE is enough to calculate the HASH which should be equal to and is send within XML Object 

I am not sure if this is an error or an anomaly but probably the answer is in the getResponseParams function of Response.php. Or was it Client.php? ^_0

Sorry for the language. Not native

**Comment by drealecs** [comment]
Thank you,
I think I have a glimpse of what's wrong. I'll try to make soon.
Please make sure you use composer for easier update of the code.

**Comment by muratunal** [comment]
The code below
```
if (property_exists($xmlObject, 'HASH')) {
		    $response->setHash((string)$xmlObject->HASH);
		}
```
on Client.php@getResponse method. When you disable this part,  exception is permanently gone. 

But this seems to me as an wrong approach. Looking foward to your solution. Thank you

**Comment by drealecs** [comment]
Yes, that's the wrong approach.
The good approach is to sign all the parameters coming in the request. The current implementation is not correct and needs some changes. I'll find some time to fix this in few days. Sorry for the delay.

**Comment by drealecs** [comment]
Have a look at the code in branch fix-TR-parameters: https://github.com/PayU/alu-client-php/tree/fix-TR-parameters. It would be greate if you could test it out and check if it fixed you problem.
I'm planing to merge the pull request #11 on Tuesday and create a new release.

**Comment by drealecs** [comment]
Unfortunately, I discovered some more optionally activated response parameters that are not handled correctly. I'll take care of this soon but the previous Tuesday plan is not valid anymore

**Comment by muratunal** [comment]
Sorry for the delay, this seems to work fine.I have done several tests with fake / genuine credit cards. They all response well for both test and production env. 

Thanks a lot for your effort. :)

**Comment by makbulut** [comment]
Hi, the last changes about extra TR params fixed "HASH mismatch" problems. Will you merge the branch to master ?

And also could you add getAdditionalResponseParameters method to Response class plz.

Regards.

**Comment by drealecs** [comment]
There is a new release published: v1.1.
Thank you for your help.

**Comment by sajidunnar** [comment]
@drealecs  Alex I am still getting the same issue , running v 1.1. 
I debug the code and found that our generated hash code is different then the response hash code

What could be the solution ?

**Comment by drealecs** [comment]
Hi @sajidunnar 
Can you open a new issue because the cause of response hash mismatch is probably different?
Can you give an example of code you used? What features of the ALU are you using?

**Comment by sajidunnar** [comment]
Thanks let me create issue and sending u the whole details u asked.

**Comment by drealecs** [comment]
Hi @sajidunnar,
You didn't open an issue. Are you still having problems?
Thanks!

**Comment by sajidunnar** [comment]
@drealecs Sorry for late reply , I found that I was not sending product pricing correctly so extension is working all great 
Thanks!
